export const LOGIN_USUARIO = 'LOGIN_USUARIO';
export const LOGOUT_USUARIO = 'LOGOUT_USUARIO';

export const LOGOUT_CURRICULO = 'LOGOUT_CURRICULO';
export const PREENCHE_CURRICULO_USARIO_LOGADO = 'PREENCHE_CURRICULO_USARIO_LOGADO';
export const PREENCHE_CURRICULO = 'PREENCHE_CURRICULO';